<project name="MPFS_DISCOVERY" version="1.2">
    <ProjectDirectory>
        /home/ubuntu/GEMMCNN/temp/fp_prog_2/MPFS_DISCOVERY
    </ProjectDirectory>
    <View>
        ChainView
    </View>
    <LiberoTargetDevice>
        
    </LiberoTargetDevice>
    <LogFile>
        /home/ubuntu/GEMMCNN/temp/fp_prog_2/MPFS_DISCOVERY/MPFS_DISCOVERY.log
    </LogFile>
    <SerializationOption>
        Skip
    </SerializationOption>
    <ProgrammingInterface>
        JTAGMode
    </ProgrammingInterface>
    <programmer status="enable" type="FlashPro5" port="usbE2009P63QX (USB 2.0)" host="">
        <name>
            E2009P63QX
        </name>
        <id>
            E2009P63QX
        </id>
    </programmer>
    <Servers>
    </Servers>
    <configuration>
        <Hardware>
            <FlashPro>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
                <Vddl/>
                <Vdd>
2500                </Vdd>
            </FlashPro>
            <FlashProLite>
                <TCK>
                    4000000
                </TCK>
                <Vpp/>
                <Vpn/>
            </FlashProLite>
            <FlashPro3>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro3>
            <FlashPro4>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    FreeRunningClk
                </ClkMode>
            </FlashPro4>
            <FlashPro5>
                <TCK>
                    4000000
                </TCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro5>
            <FlashPro6>
                <TCK>
                    4000000
                </TCK>
                <SCK>
                    20000000
                </SCK>
                <ClkMode>
                    DiscreteClk
                </ClkMode>
            </FlashPro6>
        </Hardware>
        <Device type="ACTEL">
            <Name>
                MPFS095T
            </Name>
            <Custom>
                MPFS095T
            </Custom>
            <SpiFlashFile>
                
            </SpiFlashFile>
            <SpiFlashSelectedAction>
                
            </SpiFlashSelectedAction>
            <Algo type="PDB">
                <filename>
                    /home/ubuntu/GEMMCNN/temp/fp_prog_2/MPFS_DISCOVERY/MPFS_DISCOVERY.ppd
                </filename>
                <local>
                    projectData/MPFS_DISCOVERY.ppd
                </local>
                <SelectedAction>
                    PROGRAM
                </SelectedAction>
                <DeselectedProcedure>
                    DO_VERIFY
                </DeselectedProcedure>
                <Action name="PROGRAM" deselectedProcedures="DO_VERIFY">
                </Action>
            </Algo>
        </Device>
        <Algo type="unknown">
            <irlength>
                0
            </irlength>
            <MaxTCK>
                0
            </MaxTCK>
        </Algo>
    </configuration>
</project>
